# Data Science 
Data science done by Alpha

In [ ]:
from matplotlib import pyplot as plt
import pandas as pd

# a. Load the file and display the first 5 rows
df = pd.read_csv("sales-dataset.csv", encoding="latin-1")  # adjust encoding if needed

print("The shape of the data:", df.shape)
print("\nFirst 5 rows:")
print(df.head())

# b. Rename columns
df = df.rename(columns={
    "QUANTITYORDERED": "Quantity Ordered",
    "PRICEEACH": "Price Each",
    "SALES": "Sales Amount"
})

print("\nColumns after renaming:")
print(df.columns)

# c. Add a Performance column
def categorize_performance(sales):
    if sales < 1000:
        return "Low"
    elif 1000 <= sales <= 4999:
        return "Medium"
    else:
        return "High"

df["Performance"] = df["Sales Amount"].apply(categorize_performance)

print("\nFirst 5 rows with Performance column:")
print(df.head())

# d. Scatter plot of Quantity Ordered vs Sales Amount
x = df["Quantity Ordered"]
y = df["Sales Amount"]

plt.figure(figsize=(8,6))
plt.scatter(x, y, c='blue', alpha=0.5)
plt.title("Quantity Ordered vs Sales Amount")
plt.xlabel("Quantity Ordered")
plt.ylabel("Sales Amount")
plt.grid(True)
plt.show()

# Optional: describe the relationship
print("\nObservation: From the scatter plot, you can observe that as the Quantity Ordered increases, the Sales Amount generally increases, showing a positive correlation. Some variation may exist due to differences in Price Each.")

# e. Save the final dataset to a

The shape of the data: (2823, 25)

First 5 rows:
   ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES  \
0        10107               30      95.70                2  2871.00
1        10121               34      81.35                5  2765.90
2        10134               41      94.74                2  3884.34
3        10145               45      83.26                6  3746.70
4        10159               49     100.00               14  5205.27

         ORDERDATE   STATUS  QTR_ID  MONTH_ID  YEAR_ID  ...  \
0   2/24/2003 0:00  Shipped       1         2     2003  ...
1    5/7/2003 0:00  Shipped       2         5     2003  ...
2    7/1/2003 0:00  Shipped       3         7     2003  ...
3   8/25/2003 0:00  Shipped       3         8     2003  ...
4  10/10/2003 0:00  Shipped       4        10     2003  ...

                    ADDRESSLINE1  ADDRESSLINE2           CITY STATE  \
0        897 Long Airport Avenue           NaN            NYC    NY
1             59 rue de l'Abbaye           NaN          Reims   NaN
2  27 rue du Colonel Pierre Avia           NaN          Paris   NaN
3             78934 Hillside Dr.           NaN       Pasadena    CA
4                7734 Strong St.           NaN  San Francisco    CA

  POSTALCODE COUNTRY TERRITORY CONTACTLASTNAME CONTACTFIRSTNAME DEALSIZE
0      10022     USA       NaN              Yu             Kwai    Small
1      51100  France      EMEA         Henriot             Paul    Small
2      75508  France      EMEA        Da Cunha           Daniel   Medium
3      90003     USA       NaN           Young            Julie   Medium
4        NaN     USA       NaN           Brown            Julie   Medium

[5 rows x 25 columns]

Columns after renaming:
Index(['ORDERNUMBER', 'Quantity Ordered', 'Price Each', 'ORDERLINENUMBER',
       'Sales Amount', 'ORDERDATE', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID',
       'PRODUCTLINE', 'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE',
       'ADDRESSLINE1', 'ADDRESSLINE2', 'CITY', 'STATE', 'POSTALCODE',
       'COUNTRY', 'TERRITORY', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME',
       'DEALSIZE'],
      dtype='object')

First 5 rows with Performance column:
   ORDERNUMBER  Quantity Ordered  Price Each  ORDERLINENUMBER  Sales Amount  \
0        10107                30       95.70                2       2871.00
1        10121                34       81.35                5       2765.90
2        10134                41       94.74                2       3884.34
3        10145                45       83.26                6       3746.70
4        10159                49      100.00               14       5205.27

         ORDERDATE   STATUS  QTR_ID  MONTH_ID  YEAR_ID  ... ADDRESSLINE2  \
0   2/24/2003 0:00  Shipped       1         2     2003  ...          NaN
1    5/7/2003 0:00  Shipped       2         5     2003  ...          NaN
2    7/1/2003 0:00  Shipped       3         7     2003  ...          NaN
3   8/25/2003 0:00  Shipped       3         8     2003  ...          NaN
4  10/10/2003 0:00  Shipped       4        10     2003  ...          NaN

            CITY STATE POSTALCODE COUNTRY TERRITORY CONTACTLASTNAME  \
0            NYC    NY      10022     USA       NaN              Yu
1          Reims   NaN      51100  France      EMEA         Henriot
2          Paris   NaN      75508  France      EMEA        Da Cunha
3       Pasadena    CA      90003     USA       NaN           Young
4  San Francisco    CA        NaN     USA       NaN           Brown

  CONTACTFIRSTNAME DEALSIZE Performance
0             Kwai    Small         Low
1             Paul    Small         Low
2           Daniel   Medium      Medium
3            Julie   Medium      Medium
4            Julie   Medium      Medium

[5 rows x 26 columns]